# 系统配置
system:
  title: 智能充电桩调度计费系统
  version: 1.0.0
  debug: true
  host: 0.0.0.0
  port: 8000

# 数据库配置
database:
  host: localhost
  port: 3306
  user: root
  password: 20031216cyh
  database: smart_charge
  charset: utf8mb4

# 充电站参数
station:
  # 快充桩数量
  FastChargingPileNum: 2
  # 慢充桩数量
  TrickleChargingPileNum: 3
  # 等候区车位容量
  WaitingAreaSize: 6
  # 每桩排队队列长度
  ChargingQueueLen: 2
  # 单桩功率(快充) kWh/h
  FastPower: 30
  # 单桩功率(慢充) kWh/h
  SlowPower: 7
  # 服务费单价 元/kWh
  ServiceRate: 0.8
  # 调度策略 (default: 默认调度, batch_mode: 单次调度总充电时长最短, bulk_mode: 批量调度总充电时长最短)
  ScheduleStrategy: default
  # 批量调度时的车辆数量，仅在bulk_mode模式下有效
  BulkScheduleSize: 10

# 充电时段费率
rate:
  # 峰时 (1.0元/度，10:00~15:00，18:00~21:00)
  peak:
    price: 1.0
    periods:
      - ["10:00", "15:00"]
      - ["18:00", "21:00"]
  # 平时 (0.7元/度，7:00~10:00，15:00~18:00，21:00~23:00)
  normal:
    price: 0.7
    periods:
      - ["07:00", "10:00"]
      - ["15:00", "18:00"]
      - ["21:00", "23:00"]
  # 谷时 (0.4元/度，23:00~次日7:00)
  valley:
    price: 0.4
    periods:
      - ["23:00", "07:00"] 